package legalform

import "strings"

// Aliases represents a data structure that defines country-specific
// aliases for legal forms.
//
// In most cases, you want to simply use the predefined DefaultAliases instance.
type Aliases map[string]map[string]string

// Find returns the alias for the provided legal form if available.
//
// The returned alias is a cleaned text, e.g. it will not contain special
// characters or white spaces.
//
// If no alias was found, then the cleaned version of the legal form is returned.
func (l Aliases) Find(country, legalForm string) string {
	legalForm = strings.ReplaceAll(clean(legalForm), " ", "")
	country = strings.ToUpper(country)
	alias := l[country][legalForm]
	if alias != "" {
		return alias
	}
	alias = l["*"][legalForm]
	if alias != "" {
		return alias
	}
	return legalForm
}

// DefaultAliases is a list of country specific legal form aliases.
var DefaultAliases = Aliases{
	"*": map[string]string{
		"limited":      "ltd",
		"incorporated": "inc",
		"corp":         "corp",
	},
	"AT": map[string]string{
		"gesmbh":                             "gmbh",
		"stillegesellschaft":                 "stg",
		"gesellschaftmitbeschränkterhaftung": "gmbh",
		"offenehandelsgesellschaft":          "ohg",
		"europäischegesellschaft":            "se",
		"europäischegenossenschaft":          "sce",
		"kommanditerwerbsgesellschaft":       "keg",
		"aktiengesellschaft":                 "ag",
		"offenegesellschaft":                 "og",
		"offeneerwerbsgesellschaft":          "oeg",
		"europäischegesellschaftse":          "se",
		"europäischegenossenschaftsce":       "sce",
		"einzelunternehmer":                  "eu",
		"kommanditgesellschaft":              "kg",
		"gesellschaftdesbürgerlichenrechts":  "gesbr",
	},
	"NO": map[string]string{
		"europeisksamvirkeforetak":         "sce",
		"ansvarligselskap":                 "ans",
		"kommunaltforetak":                 "kf",
		"samvirkeforetak":                  "sa",
		"kommandittselskap":                "ks",
		"norskregistrertutenlandskforetak": "nuf",
		"eøfg":                             "eofg",
		"borettslag":                       "brl",
		"europeiskselskap":                 "se",
		"interkommunaltselskap":            "iks",
		"boligbyggelag":                    "bbl",
		"ansvarligselskapdeltansvar":       "da",
		"europeiskøkonomiskforetaksgruppe": "eofg",
		"enkeltpersonforetak":              "enk",
		"allmennaksjeselskap":              "asa",
		"selskapmedbegrensetansvar":        "ba",
		"aksjeselskap":                     "as",
		"statsforetak":                     "sf",
		"fylkeskommunaltforetak":           "fkf",
	},
	"KY": map[string]string{
		"companylimitedbyguarantee":      "ltd",
		"limitedpartnership":             "lp",
		"limited":                        "ltd",
		"companylimitedbyshares":         "ltd",
		"exemptedlimiteddurationcompany": "ldc",
		"exemptedlimitedpartnership":     "elp",
		"specialeconomiczonecompany":     "sezc",
		"segregatedportfoliocompany":     "spc",
		"limitedliabilitycompany":        "llc",
	},
	"SE": map[string]string{
		"ideellförening":                       "if",
		"europabolag":                          "se",
		"sparbank":                             "sb",
		"europeiskekonomiskintressegruppering": "eeig",
		"trossamfund":                          "tsf",
		"ekonomiskförening":                    "ekfor",
		"kommanditbolag":                       "kb",
		"kooperativhyresrättsförening":         "khf",
		"medlemsbank":                          "mb",
		"europakooperativ":                     "sce",
		"sambruksförening":                     "sf",
		"bankaktiebolag":                       "bab",
		"försäkringsförening":                  "fof",
		"försäkringsaktiebolag":                "fab",
		"handelsbolag":                         "hb",
		"ekför":                                "ekfor",
		"ömsesidigtförsäkringsbolag":           "ofb",
		"europeiskgrupperingförterritorielltsamarbete": "egts",
		"bostadsrättsförening":                         "brf",
		"aktiebolag":                                   "ab",
	},
	"CH": map[string]string{
		"partnershipgeneral":                     "snc",
		"societàagaranzialimitata":               "sarl",
		"sociétéencommandite":                    "sc",
		"gp":                                     "snc",
		"ag":                                     "sa",
		"sagl":                                   "sarl",
		"socencommandite":                        "sc",
		"sociétéennomcollectif":                  "snc",
		"societàanonima":                         "sa",
		"societàinaccomandita":                   "sc",
		"socnomecollettivo":                      "snc",
		"companylimitedbyshares":                 "sa",
		"sociétéanonyme":                         "sa",
		"plc":                                    "sa",
		"societàagaranzialimitatasagl":           "sarl",
		"kommanditgesellsch":                     "sc",
		"kollektivgesellsch":                     "snc",
		"aktiengesellschaft":                     "sa",
		"limitedliabilitycompany":                "sarl",
		"limited":                                "sarl",
		"sociétéàresponsabilitélimitée":          "sarl",
		"ltdpartnership":                         "sc",
		"sociétéàresponsabilitélimitéesarl":      "sarl",
		"gesellschaftmitbeschränkterhaftung":     "sarl",
		"gmbh":                                   "sarl",
		"kollektivgesellschaft":                  "snc",
		"gesellschaftmitbeschränkterhaftunggmbh": "sarl",
		"limitedpartnership":                     "sc",
		"kommanditgesellschaft":                  "sc",
		"socinaccomandita":                       "sc",
		"generalpartnership":                     "snc",
		"societàinnomecollettivo":                "snc",
		"socnomcollectif":                        "snc",
	},
	"RU": map[string]string{
		"stateunitaryenterprise":      "gup",
		"generalpartnership":          "pt",
		"llc":                         "ooo",
		"ооо":                         "ooo",
		"pjsc":                        "pao",
		"productioncooperative":       "pk",
		"businesspartnership":         "khp",
		"limitedliabilitypartnership": "too",
		"llp":                         "too",
		"limitedpartnership":          "kt",
		"jsc":                         "ao",
		"cjsc":                        "zao",
		"municipalunitaryenterprise":  "mup",
	},
	"SG": map[string]string{
		"limited":                     "ltd",
		"limitedpartnership":          "lp",
		"limitedliabilitypartnership": "llp",
		"pteltd":                      "ltd",
	},
	"CR": map[string]string{
		"sociedadcivil": "ac",
		"sociedadderesponsabilidadlimitadaosociedadlimitada": "sl",
		"srl":                 "sl",
		"sociedadcolectiva":   "sc",
		"sociedadanónima":     "sa",
		"sociedadencomandita": "senc",
		"empresaindividualderesponsabilidadlimitada": "eirl",
	},
	"PH": map[string]string{
		"stockcorporation":     "inc",
		"incorporated":         "inc",
		"onepersoncorporation": "opc",
	},
	"RO": map[string]string{
		"societateîncomandităpeacţiuni":   "sca",
		"grupuleuropeandeintereseconomic": "geie",
		"organizațienonguvernamentală":    "ong",
		"societateînnumecolectiv":         "snc",
		"asociatiefamiliala":              "af",
		"societateîncomandităsimplă":      "scs",
		"societateeuropeană":              "se",
		"regieautonomă":                   "ra",
		"grupuldeintereseconomic":         "gie",
		"societatecooperativăeuropeană":   "sce",
		"societatecurăspunderelimitată":   "srl",
		"societatepeacţiuni":              "sa",
		"intreprindereindividuala":        "ii",
		"persoanafizicaindependentă":      "pfi",
		"persoanafizicaautorizata":        "pfa",
	},
	"GR": map[string]string{
		"somatiaidrimata":             "clf",
		"anónimietería":               "sa",
		"naftikieteria":               "sc",
		"εvropaikiεtaireia":           "se",
		"astikiproswpikieteria":       "sp",
		"nomikaprosopadimosioudikeou": "pl",
		"kinopraxia":                  "jv",
		"omórithmietería":             "oe",
		"eterórithmietería":           "ee",
		"eteríaperiorisméniseuthínis": "epe",
		"sinetairismos":               "coop",
		"afaniseteria":                "slp",
		"idiotikikefaleouhikieteria":  "ike",
		"simplioktisia":               "jso",
	},
	"UK": map[string]string{
		"cyf":                                   "ltd",
		"unitedkingdomeconomicinterestgrouping": "ukeig",
		"privatelimitedbyguarantee":             "ltd",
		"limited":                               "ltd",
		"ccc":                                   "plc",
		"privatelimitedcompany":                 "ltd",
		"cwmnicyfyngedigcyhoeddus":              "plc",
		"publiclimitedcompany":                  "plc",
		"societaseuropaea":                      "se",
		"cooperativesociety":                    "coop",
		"communitybenefitsociety":               "bencom",
		"europeaneconomicinterestgrouping":      "eeig",
		"partneriaethatebolrwyddcyfyngedig":     "llp",
		"pac":                                   "llp",
		"communityinterestcompany":              "cic",
		"unitedkingdomsocietas":                 "uks",
		"cyfyngedig":                            "ltd",
		"limitedpartnership":                    "lp",
		"limitedliabilitypartnership":           "llp",
	},
	"IT": map[string]string{
		"societàcooperativa":                         "sc",
		"societàinnomecollettivo":                    "snc",
		"societàeuropea":                             "se",
		"gruppoeuropeodiinteresseeconomico":          "geie",
		"srlsemplificata":                            "srls",
		"societàcooperativaeuropea":                  "sce",
		"scrl":                                       "scarl",
		"societàaresponsabilitàlimitata":             "srl",
		"societàperazioni":                           "spa",
		"societàsemplice":                            "ss",
		"societàaresponsabilitàlimitatasemplificata": "srls",
		"societàconsortilearesponsabilitàlimitata":   "scarl",
	},
	"LU": map[string]string{
		"sociétéencommanditesimple":               "secs",
		"sociétédépargnepensionàcapitalvariable":  "sepcav",
		"sociétéàresponsabilitélimitée":           "sarl",
		"sociétéàresponsabilitélimitéesimplifiée": "sarls",
		"sociétécivile":                           "sci",
		"groupementeuropéendintérêtéconomique":    "geie",
		"sociétédinvestissementàcapitalfixe":      "sicaf",
		"fondation":                               "fon",
		"entrepriseindividuelle":                  "ei",
		"associationdassurancesmutuelles":         "aam",
		"sociétéparactionssimplifiée":             "sas",
		"associationdépargnepension":              "assep",
		"associationmomentanée":                   "am",
		"sàrls":                                   "sarls",
		"sociétéencommanditespéciale":             "secsp",
		"etablissementpublic":                     "ep",
		"associationagricole":                     "aa",
		"fondcommundeplacement":                   "fcp",
		"groupementdintérêtéconomique":            "gie",
		"sociétécoopérative":                      "sc",
		"sociétéeuropéenne":                       "se",
		"sociétéencommanditeparactions":           "seca",
		"sociétédinvestissementàcapitalvariable":  "sicav",
		"associationsansbutlucratif":              "asbl",
		"sociétéanonyme":                          "sa",
		"sociétéennomcollectif":                   "senc",
		"societascooperativaeuropaea":             "sce",
	},
	"HK": map[string]string{
		"limited":            "ltd",
		"unlimited":          "ultd",
		"unltd":              "ultd",
		"limitedpartnership": "lp",
	},
	"AE": map[string]string{
		"rakeconomiczonecompany": "fzllc",
	},
	"VG": map[string]string{
		"incorporated":       "inc",
		"unlimited":          "unltd",
		"corporation":        "corp",
		"limitedpartnership": "lp",
		"unlimitedcompanythatisauthorisedtoissueshares": "unltd",
		"segregatedportfoliocompany":                    "spc",
		"limited":                                       "ltd",
	},
	"MY": map[string]string{
		"publiccompany":               "bhd",
		"berhad":                      "bhd",
		"limitedliabilitypartnership": "llp",
		"privatecompany":              "sdnbhd",
		"pteltd":                      "sdnbhd",
		"sendirianberhad":             "sdnbhd",
		"limited":                     "ltd",
	},
	"EC": map[string]string{
		"compañíaennombrecolectivo":                     "cncol",
		"compañíaencomanditasimpleydivididaporacciones": "ccsda",
		"compañíaanónima":                               "sa",
		"compañíadeeconomíamixta":                       "cemix",
		"compañíaderesponsabilidadlimitada":             "cialtda",
	},
	"DO": map[string]string{
		"sociedadencomanditasimple":                  "senc",
		"sociedadanónimasimplificada":                "sas",
		"empresaindividualderesponsabilidadlimitada": "eirl",
		"sociedadderesponsaibilidadlimitada":         "srl",
		"sociedadanónima":                            "sa",
	},
	"US": map[string]string{
		"rlllp":                                         "lllp",
		"mutualbenefitenterprise":                       "mbe",
		"cooperative":                                   "coop",
		"professionalassociation":                       "pa",
		"federalsavingsassociation":                     "fsa",
		"limitedliabilitycompany":                       "llc",
		"cooperativecorporation":                        "coop",
		"generalcooperativeassociation":                 "coop",
		"businesstrust":                                 "bt",
		"communitydevelopmentcorporation":               "cdc",
		"realestateinvestmenttrusts":                    "reit",
		"limited":                                       "ltd",
		"limitedliabilitylimitedpartnership":            "lllp",
		"publicbenefitcorporationprofit":                "pbc",
		"professionallimitedliabilitycompany":           "pllc",
		"corporation":                                   "corp",
		"statutorypublicbenefitlimitedliabilitycompany": "spbllc",
		"generalpartnership":                            "gp",
		"rllp":                                          "llp",
		"professionalcorporation":                       "pc",
		"limitedcooperativeassociation":                 "lca",
		"registeredlimitedliabilitypartnership":         "llp",
		"limitedpartnership":                            "lp",
		"limitedliabilitypartnership":                   "llp",
		"savingsloanassociation":                        "sl",
		"registeredlimitedliabilitylimitedpartnership":  "lllp",
		"incorporated":                                  "inc",
		"forprofitcorporationprofessional":              "pc",
		"commercialregisteredagent":                     "cra",
		"statutoryfoundation":                           "sf",
	},
	"ES": map[string]string{
		"sociedadanonimaprofesional":                   "sap",
		"sociedadcooperativaprofesional":               "scoopp",
		"fondodepensiones":                             "fp",
		"sociedadcolectiva":                            "sc",
		"sociedadcomanditariasimple":                   "senc",
		"scom":                                         "senc",
		"srll":                                         "sll",
		"sociedadesdeinversioninmobiliaria":            "sii",
		"fondodecapitalriesgopyme":                     "fcrpyme",
		"agrupaciondeintereseconomico":                 "aie",
		"sociedadlimitadaprofesional":                  "slp",
		"instituciondeinversioncolectiva":              "iic",
		"sociedadlimitadaunipersonal":                  "slu",
		"src":                                          "sc",
		"sociedadcomanditariasimpleprofesional":        "sencp",
		"mutualidaddeprevisionsocial":                  "mps",
		"sociedaddecapitalriesgo":                      "scr",
		"sociedaddeinversióndecapitalvariable":         "sicav",
		"sociedadanonimaeuropea":                       "se",
		"sociedadderesponsabilidadlimitada":            "sl",
		"fondodeinversionenactivosdelmercadomonetario": "fiamm",
		"sociedadcomanditariaporacciones":              "scompa",
		"sociedadcooperativaeuropea":                   "sce",
		"sociedadagraríadetrasformación":               "sat",
		"sociedadanonima":                              "sa",
		"sociedadlimitadadenuevaempresa":               "slne",
		"emprendedorderesponsabilidadlimitada":         "erl",
		"sociedadcomanditariaporaccionesprofesional":   "scompap",
		"scoope":                                   "sce",
		"srcp":                                     "scp",
		"agrupacioneuropeadeintereseconomico":      "aeie",
		"sociedaddecapitalriesgopyme":              "scrpyme",
		"srlp":                                     "slp",
		"fondosdeinversioninmobiliaria":            "fii",
		"fondodeinversionmobiliaria":               "fim",
		"sociedadcooperativa":                      "scoop",
		"sociedadcolectivaprofesional":             "scp",
		"sociedaddegarantiareciproca":              "sgr",
		"sociedadlimitadalaboral":                  "sll",
		"sociedadderesponsabilidadlimitadalaboral": "sll",
		"fondodecapitalriesgo":                     "fcr",
		"sociedadanonimalaboral":                   "sal",
		"fondodeinversion":                         "fi",
		"scomp":                                    "sencp",
		"sociedadregularcolectivaprofesional":      "scp",
		"srl":                                      "sl",
	},
	"NL": map[string]string{
		"naamlozevennootschap":      "nv",
		"commanditairevennootschap": "cv",
		"coöperatie":                "coop",
		"beslotenvennootschapmetbeperkteaansprakelijkheid": "bv",
		"europeeseconomischsamenwerkingsverband":           "eesv",
		"vennootschaponderfirma":                           "vof",
		"europesenaamlozevennootschapsocietaseuropaea":     "se",
		"onderlingewaarborgmaatschappij":                   "owm",
		"rechtspersooninoprichting":                        "rpio",
		"verenigingvaneigenaars":                           "vve",
		"coöp":                                             "coop",
		"societascooperativaeuropaea":                      "sce",
	},
	"MX": map[string]string{
		"sociedadanónimapromotoradeinversióndecapitalvariable":  "sapidecv",
		"sociedadcooperativadeahorroypréstamodecapitalvariable": "scdeapdecv",
		"sociedadcivil":                                                "sc",
		"sociedadanónimabursátil":                                      "sab",
		"sociedadporaccionessimplificada":                              "sas",
		"institucióndeasistenciaprivada":                               "iap",
		"sociedadderesponsabilidadlimitada":                            "sderl",
		"sociedadnacionaldecrédito":                                    "snc",
		"sociedaddeproducciónruralderesponsabilidadlimitada":           "spr",
		"sociedadanónimapromotoradeinversiónbursátildecapitalvariable": "sapibdecv",
		"sociedadcooperativalimitada":                                  "scl",
		"empresaproductivadelestado":                                   "epe",
		"sociedadderesponsabilidadlimitadadecapitalvariable":           "sderldecv",
		"sociedadanónimapromotoradeinversióndecapitalvariablesociedadfinancieradeobjetomúltipleentidadnoregulada": "sapidecv",
		"sociedaddeproducciónruralderesponsabilidadlimitadadecapitalvariable":                                     "sprderldecv",
		"sociedadencomanditaporacciones":                                     "sencpora",
		"sociedadanónimadecapitalvariable":                                   "sadecv",
		"agrupacionesfinancieras":                                            "af",
		"sociedadanónima":                                                    "sa",
		"unidadagrícolaindustrialdelamujer":                                  "uaim",
		"sociedadderesponsabilidadlimitadamicroindustrial":                   "sderlmi",
		"sociedadcooperativaderesponsabilidadlimitadadecapitalvariable":      "scderldecv",
		"sociedadanónimapromotoradeinversiónbursátil":                        "sapib",
		"sociedadencomanditaporaccionesdecapitalvariable":                    "sencporadecv",
		"sociedadporaccionessimplificadadecapitalvariable":                   "sasdecv",
		"sociedadcooperativadeahorroypréstamo":                               "scdeap",
		"sociedadcooperativalimitadadecapitalvariable":                       "scldecv",
		"sociedadderesponsabilidadlimitadadeinteréspúblicodecapitalvariable": "sderldeipdecv",
		"sociedadanónimabursátildecapitalvariable":                           "sabdecv",
		"sociedadencomanditasimple":                                          "senc",
		"asociacióncivil":                                                    "ac",
		"sociedadencomanditasimpledecapitalvariable":                         "sencdecv",
		"sociedaddesolidaridadsocial":                                        "sdess",
		"sociedadanónimapromotoradeinversión":                                "sapi",
	},
	"TR": map[string]string{
		"komşti":          "komsti",
		"limitedşirket":   "ltdsti",
		"ltdşti":          "ltdsti",
		"anonimşirket":    "as",
		"aş":              "as",
		"kollektifşirket": "kollsti",
		"kollşti":         "kollsti",
		"komanditşirket":  "komsti",
	},
	"BG": map[string]string{
		"ednolichentargovets": "et",
		"sie":                 "sd",
		"druzhestvouchredenopozakonazazadalzheniyataidogovorite": "dzzd",
		"sabiratelnodruzhestvo":                                  "sd",
		"sadruzhie":                                              "sd",
		"aktsionernodruzhestvosasspetsialnainvestitsionnatsel":   "adsic",
		"evropeyskoobedineniepoikonomicheskiinteresi":            "eeig",
		"komanditnodruzhestvo":                                   "kd",
		"evropeyskokooperativnodruzhestvo":                       "ekd",
		"aktsionernodruzhestvo":                                  "ad",
		"druzhestvosogranichenaotgovornost":                      "ood",
		"ednolichnodruzhestvosogranichenaotgovornost":            "eood",
		"ednolichnoaktsionernodruzhestvo":                        "ead",
		"komanditnodruzhestvosaktsii":                            "kda",
		"evropeyskodruzhestvo":                                   "ed",
	},
	"PK": map[string]string{
		"limitedliabilitypartnership": "llp",
		"privatelimitedcompany":       "pvtltd",
		"companylimitedbyguarantee":   "guaranteeltd",
		"unlimitedcompany":            "ultd",
		"unlimited":                   "ultd",
		"unltd":                       "ultd",
		"publiclimitedcompany":        "ltd",
		"limited":                     "ltd",
	},
	"FI": map[string]string{
		"säätiö":                               "sr",
		"ab":                                   "oy",
		"eurooppalainentaloudellinenetuyhtymä": "etey",
		"publiktaktiebolag":                    "oyj",
		"europaandelslag":                      "sce",
		"eurooppayhtiö":                        "se",
		"aktiebolag":                           "oy",
		"andelslag":                            "osk",
		"kb":                                   "ky",
		"julkinenosakeyhtiö":                   "oyj",
		"abp":                                  "oyj",
		"osakeyhtiö":                           "oy",
		"anl":                                  "osk",
		"kommandiittiyhtiö":                    "ky",
		"kommanditbolag":                       "ky",
		"europabolag":                          "se",
		"osuuskunta":                           "osk",
		"europeiskekonomiskintresseguppering":  "etey",
		"eeig":                                 "etey",
		"eurooppaosuuskunta":                   "sce",
		"stiftelse":                            "sr",
	},
	"CZ": map[string]string{
		"evropskéhospodářskézájmovésdružení": "ehzs",
		"evropskádružstevníspolečnost":       "sce",
		"evropskáspolečnost":                 "se",
	},
	"FR": map[string]string{
		"sociétéparactionssimplifiée":          "sas",
		"groupementeuropéendintérêtéconomique": "geie",
		"sociétéanonyme":                       "sa",
		"sociétéenlibrepartenariat":            "slp",
		"sociétéeuropéenne":                    "se",
	},
	"PT": map[string]string{
		"societascooperativaeuropaea":            "sce",
		"agrupamentoeuropeudeinteresseeconómico": "aeie",
		"sociedadeanónimaeuropeia":               "se",
	},
	"CO": map[string]string{
		"empresaunipersonal":                 "eu",
		"sociedadporaccionessimplificada":    "sas",
		"sociedadesagrariasdetransformación": "sat",
		"sociedadanónima":                    "sa",
		"sociedadencomanditasimple":          "ciasenc",
		"cíasenc":                            "ciasenc",
		"sociedadencomanditaporacciones":     "ciasca",
		"cíasca":                             "ciasca",
		"sociedadderesponsabilidadlimitada":  "ltda",
	},
	"ID": map[string]string{
		"perusahaanperseroan":                        "persero",
		"perseroanterbataspenanamanmodalasing":       "ptpma",
		"perseroanterbataspenanamanmodaldalamnegeri": "pt",
		"ptpmdn":                    "pt",
		"perseroanterbuka":          "tbk",
		"commanditairevennootschap": "cv",
		"firma":                     "fa",
		"perusahaanumum":            "perum",
	},
	"PL": map[string]string{
		"spółkakomandytowa":                            "spk",
		"spółkaakcyjna":                                "sa",
		"spółkaeuropejska":                             "se",
		"spółkakomandytowoakcyjna":                     "ska",
		"otwartyfunduszemerytalny":                     "ofe",
		"spółkajawna":                                  "sj",
		"spj":                                          "sj",
		"prostaspółkaakcyjna":                          "psa",
		"towarzystwoubezpieczeńwzajemnych":             "tuw",
		"spółkacywilna":                                "sc",
		"spółkapartnerska":                             "spp",
		"europejskiezgrupowanieinteresówgospodarczych": "ezig",
		"spółkazograniczonąodpowiedzialnością":         "spzoo",
	},
	"NZ": map[string]string{
		"limitedpartnership":        "lp",
		"limitedliabilitycompany":   "ltd",
		"limited":                   "ltd",
		"cooperativecompany":        "coop",
		"unlimitedliabilitycompany": "ultd",
		"unltd":                     "ultd",
	},
	"DE": map[string]string{
		"gemeinnützigegesellschaftmitbeschränkterhaftung": "ggmbh",
		"societaseuropaea":                      "se",
		"gesellschaftmitbeschränkterhaftung":    "gmbh",
		"kommanditgesellschaft":                 "kg",
		"reitaktiengesellschaft":                "reitag",
		"eingetragenekauffrau":                  "ek",
		"ekfm":                                  "ek",
		"eingetragenerverein":                   "ev",
		"europäischegenossenschaft":             "sce",
		"gemeinnützigeaktiengesellschaft":       "gag",
		"ughaftungsbeschränkt":                  "ug",
		"aktiengesellschaft":                    "ag",
		"partnerschaftsgesellschaft":            "partg",
		"eingetragenegenossenschaft":            "eg",
		"ekffr":                                 "ek",
		"kommanditgesellschaftaufaktien":        "kgaa",
		"offenehandelsgesellschaft":             "ohg",
		"unternehmergesellschaft":               "ug",
		"gesellschaftbürgerlichenrechts":        "gbr",
		"investmentaktiengesellschaft":          "invag",
		"eingetragenerkaufmann":                 "ek",
		"versicherungsvereinaufgegenseitigkeit": "vvag",
		"gesmbh":                                "gmbh",
		"partnerschaftsgesellschaftmitbeschränkterberufshaftung": "partgmbb",
		"europäischewirtschaftlicheinteressenvereinigung":        "ewiv",
		"europäischeaktiengesellschaft":                          "se",
	},
	"CA": map[string]string{
		"associationcoopérative":           "coop",
		"sociétéàintérêtcommunautaire":     "cic",
		"limitedcorporation":               "ltd",
		"sec":                              "lp",
		"coopérative":                      "coop",
		"sociétéàresponsabilitéfiduciaire": "sarf",
		"cp":                               "pc",
		"cooperativeassociation":           "coop",
		"incorporated":                     "inc",
		"limitedliabilitypartnership":      "llp",
		"limited":                          "ltd",
		"limitée":                          "ltd",
		"sociétéennomcollectifàresponsabilitélimitée": "llp",
		"professionalcorporation":                     "pc",
		"sociétéencommandite":                         "lp",
		"sic":                                         "cic",
		"unlimitedliabilitycorporation":               "ulc",
		"corporationprofessionnelle":                  "pc",
		"communityinterestcompany":                    "cic",
		"unlimitedcompany":                            "ulc",
		"ltée":                                        "ltd",
		"limitedpartnership":                          "lp",
		"cooperative":                                 "coop",
		"corporation":                                 "corp",
		"sociétéparactions":                           "sa",
		"sencrl":                                      "llp",
	},
	"CL": map[string]string{
		"sociedadlegalminera":                        "slm",
		"asociacióngremial":                          "ag",
		"sociedadderesponsabilidadlimitada":          "srl",
		"sociedadporacciones":                        "spa",
		"sociedadanónima":                            "sa",
		"sociedadcontractualminera":                  "scm",
		"empresaindividualderesponsabilidadlimitada": "eirl",
	},
	"PA": map[string]string{
		"microempresaderesponsabilidadlimitada": "mrl",
		"sociedadanónima":                       "sa",
		"sociedadcivil":                         "sc",
		"sociedadderesponsabilidadlimitada":     "srl",
		"fundacióndeinterésprivado":             "fip",
	},
	"AU": map[string]string{
		"cooperativeltd":                  "coop",
		"coopltd":                         "coop",
		"noliability":                     "nl",
		"indigenouscorporation":           "rntbc",
		"cooperative":                     "coop",
		"cooperativelimited":              "coop",
		"incorporated":                    "inc",
		"limited":                         "ltd",
		"cooplimited":                     "coop",
		"noliabilitycompany":              "nl",
		"ptyltd":                          "pty",
		"incorporatedassociation":         "inc",
		"limitedpartnership":              "lp",
		"publiccompanylimitedbyguarantee": "ltd",
		"limitedproprietarycompany":       "pty",
	},
	"BR": map[string]string{
		"empresapública":                 "ep",
		"sociedadeemcomdanditasimples":   "scs",
		"sociedadeanônima":               "sa",
		"companhia":                      "sa",
		"cia":                            "sa",
		"sociedadeemcontadeparticipação": "scp",
		"sociedadeemnomecoletivo":        "snc",
		"sociedadesimples":               "ss",
		"fundação":                       "fund",
		"associação":                     "assoc",
		"empresaindividualderesponsabilidadelimitada": "eireli",
		"sociedadelimitada":                           "ltda",
		"sociedadeemcomanditaporações":                "ca",
	},
	"ZA": map[string]string{
		"personalliabilitycompany": "inc",
		"incorporated":             "inc",
		"publiccompany":            "ltd",
		"limited":                  "ltd",
		"closecorporation":         "cc",
		"privatecompany":           "ptyltd",
		"nonprofitcompany":         "npc",
		"stateownedcompany":        "soc",
	},
	"PE": map[string]string{
		"sociedadcomercialderesponsabilidadlimitada": "srl",
		"sociedaanónimaabierta":                      "saa",
		"sociedadcivil":                              "scivil",
		"sociedadencomanditasimple":                  "senc",
		"sociedadporaccionescerradasimplificada":     "sacs",
		"sociedadcivilderesponsabilidadlimitada":     "scivilderl",
		"sociedadanónimacerrada":                     "sac",
		"empresaindividualderesponsabilidadlimitada": "eirl",
		"sociedaanónima":                             "sa",
		"sociedadencomanditaporacciones":             "sencpora",
		"sociedadcolectiva":                          "sc",
	},
	"HU": map[string]string{
		"nyilvánosanműködőrészvénytársaság": "nyrt",
		"zártkörűenműködőrészvénytársaság":  "zrt",
		"részvénytársaság":                  "rt",
		"közhasznútársaság":                 "kht",
		"közkeresetitársaság":               "kkt",
		"korlátoltfelelősségűtársaság":      "kft",
		"takarékéshitelszövetkezet":         "hsz",
		"tksz":                              "hsz",
		"országosbetétbiztosításialap":      "oba",
		"európaigazdaságiegyesülés":         "ege",
		"betétitársaság":                    "bt",
		"szövetségkivévesportszövetség":     "kbe",
		"európairészvénytársaság":           "se",
	},
	"IE": map[string]string{
		"cn":                                          "ulc",
		"grupaileorpachumleaseacnamaioch":             "eeig",
		"companylimitedbyguarantee":                   "clg",
		"cti":                                         "ilp",
		"irishcollectiveassetmanagementvehicle":       "icav",
		"cuideachtafaoitheorainnráthaíochta":          "clg",
		"privateunlimitedcompany":                     "ulc",
		"limited":                                     "ltd",
		"privatecompanylimitedbyshares":               "ltd",
		"publiclimitedcompany":                        "plc",
		"designatedactivitycompany":                   "dac",
		"publicunlimitedcompanythathasnosharecapital": "pulc",
		"teoranta":                                    "ltd",
		"publicunlimitedcompany":                      "puc",
		"cpt":                                         "plc",
		"europeaneconomicinterestgrouping":            "eeig",
		"societaseuropaea":                            "se",
		"cuideachtaphríobháideachtheoranta":           "ltd",
		"cuideachtaphoiblítheoranta":                  "plc",
		"gele":                                        "eeig",
		"cga":                                         "dac",
		"cuideachtaneamhtheoranta":                    "ulc",
		"limitedcompany":                              "ltd",
		"teo":                                         "ltd",
		"investmentlimitedpartnership":                "ilp",
		"cuideachtaghníomhaíochtaainmnithe":           "dac",
		"ctr":                                         "clg",
		"comhpháirtíochttheorantainfheistíochta": "ilp",
	},
	"IN": map[string]string{
		"publiclimitedcompany":        "ltd",
		"limited":                     "ltd",
		"limitedliabilitypartnership": "llp",
		"privatelimitedcompany":       "pvtltd",
	},
	"DK": map[string]string{
		"iværksætterselskab":              "ivs",
		"interessentskab":                 "is",
		"anpartsselskab":                  "aps",
		"andelsselskabmedbegrænsetansvar": "amba",
		"foreningmedbegrænsetansvar":      "fmba",
		"aktieselskab":                    "as",
		"europæiskselskab":                "seselskab",
		"partnerselskab":                  "ps",
		"europæiskandelsselskab":          "sceselskab",
		"selskabmedbegrænsetansvar":       "smba",
		"kommanditselskab":                "ks",
		"europæiskøkonomiskfirmagruppe":   "eofg",
		"eøfg":                            "eofg",
	},
	"AR": map[string]string{
		"sociedadcolectiva":               "soccol",
		"sociedadanonima":                 "sa",
		"sociedadanonimaunipersonal":      "sau",
		"sociedaddegarantíareciproca":     "sgr",
		"sociedadencomanditaporacciones":  "scpa",
		"sociedadderesponsalidedlimitada": "srl",
		"sociedaddelestado":               "se",
		"sociedaddecapitaleindustria":     "scei",
		"sociedadporaccionessimplificada": "sas",
		"sociedadencomanditasimple":       "scs",
		"sociedadcooperativa":             "scoop",
	},
}
